Методологии вёрстки
htmlacademy-adaptive/2166645-cat-energy-27 pull request #2
Opened 2022-11-26 14:39 UTC by Inga-e

Второй раздел: разметка 3х файлов по мобильной версии макета

2022-11-28 13:48 UTC, Dima-Dim requested changes
[source/img/clocks.svg](https://github.com/htmlacademy-adaptive/2166645-cat-energy-27/pull/2/files#diff-9954322c4d83a1394bd68fe1f9a05a69bce280084e6e43d434e325f56ebbb827) - зелёный квадрат у подобных изображения можно сделать css-ом.

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +      <button class="button selection-program__button" type="button"><span class="">Подобрать программу</span></button>
Для чего потребуется `span`?

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +      <h2 class="visually-hidden">Подбор программы питания</h2>
Для чего тут отдельная секция? Ведь всё это один логический блок.

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +            <img class="food-programs__icon" src="./img/cat_sit.svg" width="50" height="50"
На 1-ому уровне у вас был материал про то, какие изображения нужно размещать в разметку, а какие нет.

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +            <span class="food-programs__title">Похудение</span>
Если убрать лишнее, то останется просто заголовок логического блока.

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +            <span class="food-programs__catalog-chapter-name">Каталог Slim</span>
Тоже не понятно для чего `span`.

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +          <img class="food-instruction__step-icon" src="./img/leaf.svg" width="60" height="60" alt="Лист на зелёном фоне.">
Та же история с изображениями.

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +          <p class="food-instruction__step-description">Функциональное питание содержит только полезные питательные вещества.</p>
В итоге может и `p` будут не нужны.

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +        <button class="visually-hidden" type="button">Стрелки назад-вперед</button>
Кнопка которую будет не видно?

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +    <div class="main-footer__social social">
Уверена что понадобится дополнительный контейнер?

2022-11-28 13:48 UTC, Dima-Dim commented on source/index.html
> +      <ul class="social__list">
Вот эта часть получилась хорошо :)

2022-11-28 13:48 UTC, Dima-Dim commented on source/catalog.html
> +          <dl class="features__list">
Элемент `features__list` вне блока `features`. Проверять тут yoksel.github.io/html-tree/

2022-11-28 13:48 UTC, Dima-Dim commented on source/form.html
> +            <label class="cat-name__label" for="cat-name">Имя:*
Тоже элемент `cat-name__label` вне блока `cat-name`.

2022-11-28 14:11 UTC, Inga-e commented on source/index.html
> +      <h2 class="visually-hidden">Подбор программы питания</h2>
для того, чтобы потом была возможность перемещать, в т.ч. на бэкграунд. Что так нельзя оставить? я пока именно так вижу эту часть

2022-11-28 14:14 UTC, Inga-e commented on source/index.html
> +            <img class="food-programs__icon" src="./img/cat_sit.svg" width="50" height="50"
контентные в разметку или те, которые имеют состояния (меняют параметры). У меня были сомнения, что может это все-таки контентные, поэтому я разместила. Убрать?

2022-11-28 14:15 UTC, Inga-e commented on source/index.html
> +      <button class="button selection-program__button" type="button"><span class="">Подобрать программу</span></button>
для стилей, но если будет достаточно класса баттон, то уберу

2022-11-28 14:16 UTC, Inga-e commented on source/index.html
> +            <span class="food-programs__catalog-chapter-name">Каталог Slim</span>
для стилей, если лишнее, то уберу

2022-11-28 14:19 UTC, Inga-e commented on source/index.html
> +        <button class="visually-hidden" type="button">Стрелки назад-вперед</button>
я на ее место размещу элемент по перемещению влево и вправо. наверное, тогда лучше текст Стрелки назад-вперед  поместить в span  и сделать visualy-hidden?

2022-11-28 14:19 UTC, Dima-Dim commented on source/index.html
> +      <h2 class="visually-hidden">Подбор программы питания</h2>
Да можно как угодно, только в одном случае в этом есть логика документа, а в другом разметка ради стилизации.

2022-11-28 14:20 UTC, Dima-Dim commented on source/index.html
> +            <img class="food-programs__icon" src="./img/cat_sit.svg" width="50" height="50"
Расскажи в связи с чем сомнения?

2022-11-28 14:20 UTC, Inga-e commented on source/index.html
> +    <div class="main-footer__social social">
это я списала с демонстрации барбер-шопа, не знаю, понадобится или нет, посмотрим дальше

2022-11-28 14:20 UTC, Dima-Dim commented on source/index.html
> +            <span class="food-programs__catalog-chapter-name">Каталог Slim</span>
https://up.htmlacademy.ru/adaptive/27/criteries#d2

2022-11-28 14:22 UTC, Dima-Dim commented on source/index.html
> +        <button class="visually-hidden" type="button">Стрелки назад-вперед</button>
С учётом того что сейчас это невидимая кнопка в которой нет смысла, то всё будет лучше :)))

2022-11-28 14:23 UTC, Dima-Dim commented on source/index.html
> +    <div class="main-footer__social social">
Нет, всё что сейчас не нужно должно отсутствовать в коде.

2022-11-28 14:38 UTC, Inga-e commented on source/index.html
> +      <h2 class="visually-hidden">Подбор программы питания</h2>
ну тогда, может сделать в одном блоке 2 блока? как лучше?

2022-11-28 14:39 UTC, Inga-e commented on source/index.html
> +            <img class="food-programs__icon" src="./img/cat_sit.svg" width="50" height="50"
Уже разобрались :)

2022-11-28 14:40 UTC, Inga-e commented on source/index.html
> +        <button class="visually-hidden" type="button">Стрелки назад-вперед</button>
ок

2022-11-28 14:42 UTC, Inga-e commented on source/index.html
> +    <div class="main-footer__social social">
хорошо, поняла

2022-11-28 14:43 UTC, Inga-e commented on source/index.html
> +      <ul class="social__list">
Спасибо :)

2022-11-28 14:56 UTC, Inga-e commented on source/index.html
> +            <span class="food-programs__catalog-chapter-name">Каталог Slim</span>
поняла

2022-11-29 05:28 UTC, Inga-e commented on source/index.html
> +      <h2 class="visually-hidden">Подбор программы питания</h2>
Сделала 1 блок section и внутри div

2022-11-29 05:28 UTC, Inga-e commented on source/index.html
> +      <button class="button selection-program__button" type="button"><span class="">Подобрать программу</span></button>
Убрала пока

2022-11-29 09:50 UTC, Dima-Dim commented on source/index.html
> +      <h2 class="visually-hidden">Подбор программы питания</h2>
Всё вёрстка это блоки в блоках :)

2022-11-30 07:15 UTC, Dima-Dim commented on source/catalog.html
> +      <a class="main-header__logo-link-icon logo-link-icon" href="./index.html">
`logo-link-icon` выглядит как лишний блок. Обрати на это внимание при стилизации.

2022-11-30 07:15 UTC, Dima-Dim commented on source/catalog.html
> +          <button class="button main-products__order-button order-button" type="button">
`order-button` как модификатор - логично, как блок - избыточно.

2022-11-30 07:15 UTC, merged