Адаптивная сетка
htmlacademy-adaptive/2166645-cat-energy-27 pull request #4
Opened 2022-12-07 11:18 UTC by Inga-e

---
:mortar_board: [Адаптивная сетка](https://up.htmlacademy.ru/adaptive/27/user/2166645/tasks/8)

:boom: https://htmlacademy-adaptive.github.io/2166645-cat-energy-27/4/

2022-12-15 10:37 UTC, Dima-Dim requested changes
Не забывать проверяться валидатором validator.w3.org/nu/

2022-12-15 10:37 UTC, Dima-Dim commented on source/less/blocks/live-example.less
> +    margin: 0 auto;
Это свойство уже было описано выше.

2022-12-15 10:37 UTC, Dima-Dim commented on source/less/blocks/live-example.less
> +    padding: 0;
Тоже свойство которое уже и так есть.

2022-12-15 10:37 UTC, Dima-Dim commented on source/less/blocks/main-database.less
> +    padding: 0;
Нужно убрать всё избыточное.

2022-12-16 03:44 UTC, Dima-Dim commented on source/script.js
> +let navMain = document.querySelector('.main-nav');
Если переменная не меняется, то лучше использовать `const`.

2022-12-16 03:44 UTC, Dima-Dim reviewed
Не забывай обращать внимание на змечания линтера.

2022-12-16 03:52 UTC, merged

2022-12-16 07:15 UTC, Inga-e commented on source/script.js
> +let navMain = document.querySelector('.main-nav');
это я еще не знаю , как делать

2022-12-18 05:10 UTC, Dima-Dim commented on source/script.js
> +let navMain = document.querySelector('.main-nav');
Просто заменить `let` на `const`.